{
  "version": 1,
  "status": "fail",
  "message": "\n\n======================================================================\nFAIL tests.chpl: testYearNotDivisibleBy4InCommonYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:6 - assertFalse failed. Given expression is True\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy2NotDivisibleBy4InCommonYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:10 - assertFalse failed. Given expression is True\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy4NotDivisibleBy100InLeapYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:14 - assertTrue failed. Given expression is False\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy4And5IsStillALeapYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:18 - assertTrue failed. Given expression is False\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy100NotDivisibleBy400InCommonYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:22 - assertFalse failed. Given expression is True\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy100ButNotBy3IsStillNotALeapYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:26 - assertFalse failed. Given expression is True\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy400IsLeapYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:30 - assertTrue failed. Given expression is False\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy400ButNotBy125IsStillALeapYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:34 - assertTrue failed. Given expression is False\n\n======================================================================\nFAIL tests.chpl: testYearDivisibleBy200NotDivisibleBy400InCommonYear()\n----------------------------------------------------------------------\nAssertionError: in test/tests.chpl:38 - assertFalse failed. Given expression is True\n\n----------------------------------------------------------------------\nRan 9 tests\n\nFAILED (failures = 9 )"
}
